name: Loom of Tyme Sync

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours to check for updates

jobs:
  sync-loom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Loom of Tyme
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Optional: Post to Sovereign Codex
        if: ${{ secrets.SOVEREIGN_KEY != '' }}
        run: |
          curl -X POST https://sovereign-codex-node.netlify.app/api/publish \
            -H "Authorization: Bearer ${{ secrets.SOVEREIGN_KEY }}" \
            -d "{\"repo\":\"LoomofTyme\",\"message\":\"Auto-sync complete\"}"
