name: Sync Submodules
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *' # Every hour

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest from submodules
        run: |
          git submodule update --remote --merge
          git config --global user.name 'TymeBot'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Auto-sync submodules" || echo "No changes"
          git push
